services:
  frontend:
    image: ghcr.io/opendata-heilbronn/frontend:latest

    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: docker/go/backend/Dockerfile
    environment:
      BROKEN_HOST: ${BROKEN_HOST}
      BROKEN_PORT: ${BROKEN_PORT}
      CLIENTID: ${CLIENTID}
      TOPIC: ${TOPIC}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      DB_DSN: ${DB_DSN}