sonar.projectKey=lorax
sonar.sources=backend
sonar.exclusions=backend/vendor/**
sonar.tests=backend
sonar.test.inclusions=backend/**/*_test.go
sonar.go.coverage.reportPaths=backend/coverage.out
sonar.host.url=https://sonarqube.mari0.dev
