# Place your local configuration here. See
# https://mosquitto.org/man/mosquitto-conf-5.html
# for more information.

# Default listener
listener 1883

# Allow anonymous connections
allow_anonymous true

# Log to stdout
log_dest stdout