; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
extra_scripts = pre:version_inject.py

build_flags =
	-D LIBPAX_ARDUINO=1
	-D LIBPAX_BLE
	-D NO_BENCHMARK
	-D CONFIG_LIBPAX_BLECOUNT=1
	-D CONFIG_LIBPAX_WIFICOUNT=0
	-D CORE_DEBUG_LEVEL=0
	-D ENABLE_LOGGING=1
	-Os
	-Wl,-gc-sections
	-fno-exceptions
	-fno-rtti
	-ffunction-sections
	-fdata-sections
	-DCONFIG_BT_BLE_42_ONLY=1
	-DCONFIG_BT_BLE_50_FEATURES_SUPPORTED=0
	-D RADIOLIB_EXCLUDE_CC1101
	-D RADIOLIB_EXCLUDE_LLCC68
	-D RADIOLIB_EXCLUDE_LR11X0
	-D RADIOLIB_EXCLUDE_LR2021
	-D RADIOLIB_EXCLUDE_RF69
	-D RADIOLIB_EXCLUDE_SX1231
	-D RADIOLIB_EXCLUDE_SX1233
	-D RADIOLIB_EXCLUDE_SX127X
	-D RADIOLIB_EXCLUDE_SX128X
	-D RADIOLIB_EXCLUDE_NRF24
	-D RADIOLIB_EXCLUDE_EXTERNAL_RADIO
	-D RADIOLIB_EXCLUDE_FSK4
	-D RADIOLIB_EXCLUDE_HELLSCHREIBER
	-D RADIOLIB_EXCLUDE_MORSE
	-D RADIOLIB_EXCLUDE_PAGER
	-D RADIOLIB_EXCLUDE_RTTY
	-D RADIOLIB_EXCLUDE_SSTV

lib_deps =
  https://github.com/ropg/heltec_esp32_lora_v3
  https://github.com/ropg/LoRaWAN_ESP32

